# Generated by Django 3.0.5 on 2020-04-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesas', '0002_ingrediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='name',
            new_name='nombre',
        ),
    ]
