# Generated by Django 3.0.5 on 2020-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesas', '0003_auto_20200417_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(to='hamburguesas.Ingrediente'),
        ),
    ]
